name: myapp
description: "Prevent your progession with PreventO"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  supabase_flutter: ^2.5.0
  provider: ^6.1.2
  firebase_core: ^3.2.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.0.0 # Added for crash reporting
  cloud_firestore: ^5.0.0 # Added for Firestore database
  firebase_auth: ^5.0.0 # Explicitly adding firebase_auth
  url_launcher: ^6.3.0
  intl: ^0.20.2
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1
  google_sign_in: ^6.2.1 # Added for Google Sign-In
  logger: ^2.3.0 # Added for logging
  pdf: ^3.10.8 # Added for PDF generation
  printing: ^5.12.0 # Added for PDF preview/sharing
  file_picker: ^10.2.0
  mime: ^2.0.0
  fl_chart: ^1.0.0
  numberpicker: ^2.1.2
  mixpanel_flutter: ^2.0.0 # Added for Mixpanel analytics
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
