name: Flutter Web Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global submodule.recurse false

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clone Flutter repository
        run: git clone https://github.com/flutter/flutter.git -b stable

      - name: Add Flutter to path
        run: |
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
          echo "${{ github.workspace }}/flutter/dart-sdk/bin" >> $GITHUB_PATH

      - name: Remove .gitmodules file
        run: rm .gitmodules

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Accept Android licenses
        run: flutter doctor --android-licenses

      - run: flutter pub get

      - run: flutter build web --release --delete-conflicting-outputs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
